# Generated by Django 5.2.5 on 2026-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecourse',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('dev_ops', 'DevOps'), ('ai_ml', 'AI/ML'), ('cybersecurity', 'Cybersecurity'), ('cloud', 'Cloud Computing'), ('linux', 'Linux')], default='web_dev', max_length=20),
        ),
    ]
