# Generated by Django 5.2.5 on 2026-04-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCourseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='live_transactions/receipts/')),
                ('is_active', models.BooleanField(default=True)),
                ('live_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.livecourse')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_transactions', to='mainApp.profile')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='LiveCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_timing', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='weekdays', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('live_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='mainApp.livecourse')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_registrations', to='mainApp.profile')),
            ],
            options={
                'unique_together': {('profile', 'live_course')},
            },
        ),
    ]
