# Generated by Django 5.2.5 on 2026-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_livecoursetransaction_livecourseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetransaction',
            name='course_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Live')], default=0),
        ),
    ]
