# Generated by Django 6.0.2 on 2026-03-19 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='courses/')),
                ('is_live', models.BooleanField(default=False)),
                ('start_day', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('button_text', models.CharField(default='Join Batch', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, help_text='At least 6 chars: 1 uppercase, 1 lowercase, 1 number, 1 special (@$!%*?&).', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain uppercase, lowercase, number, special char, min 6 chars.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{6,}$')]),
        ),
    ]
