# Generated by Django 6.0.3 on 2026-03-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_profile_enrolled_courses_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
