# Generated by Django 6.0.3 on 2026-03-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_add_course_price'),
        ('mainApp', '0007_livecourse_price'),
    ]

    operations = [
    ]
