# Generated by Django 5.2.5 on 2026-04-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_coursedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Chapter title (e.g., 'Introduction to Python')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this chapter covers')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of chapter in the course')),
                ('is_preview', models.BooleanField(default=False, help_text='Allow non-purchased users to preview first lecture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='mainApp.course')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Lecture title (e.g., 'Installing Python')", max_length=200)),
                ('lecture_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('resource', 'Resource')], default='video', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo/Streaming URL', null=True)),
                ('video_embed_code', models.TextField(blank=True, help_text='Embed code for self-hosted videos', null=True)),
                ('resource_file', models.FileField(blank=True, help_text='PDF, PPT, or other resources', null=True, upload_to='course_resources/')),
                ('content', models.TextField(blank=True, help_text='Text content for articles or lecture notes', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lecture within chapter')),
                ('is_free_preview', models.BooleanField(default=False, help_text='Allow non-purchased users to preview this lecture')),
                ('is_downloadable', models.BooleanField(default=False, help_text='Allow users to download resources')),
                ('passing_score', models.PositiveIntegerField(default=0, help_text='Passing score percentage for quizzes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='mainApp.chapter')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='For subscription-based access', null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_lectures', models.ManyToManyField(blank=True, related_name='completed_by_users', to='mainApp.lecture')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='mainApp.course')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='mainApp.coursetransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to='mainApp.profile')),
            ],
            options={
                'ordering': ['-access_granted_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('watch_time_seconds', models.PositiveIntegerField(default=0, help_text='Total watch time in seconds')),
                ('last_watch_position', models.PositiveIntegerField(default=0, help_text='Last watched position in seconds')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz_attempts', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('user_notes', models.TextField(blank=True, help_text="User's personal notes for this lecture")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='mainApp.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress', to='mainApp.profile')),
                ('course_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress_records', to='mainApp.usercourseaccess')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'lecture')},
            },
        ),
    ]
