# Generated by Django 5.2.5 on 2026-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_course_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetransaction',
            name='course_type',
        ),
        migrations.AddConstraint(
            model_name='coursetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'course', 'status'), name='unique_pending_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='livecourseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('profile', 'live_course', 'status'), name='unique_pending_registration'),
        ),
        migrations.AddConstraint(
            model_name='livecoursetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('profile', 'live_course', 'status'), name='unique_pending_live_cart_item'),
        ),
    ]
