# Generated by Django 5.2.5 on 2026-05-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_coursetransaction_base_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions for the quiz')),
                ('quiz_type', models.CharField(choices=[('mcq', 'Multiple Choice Questions'), ('one_line', 'One Line Answer'), ('mixed', 'Mixed (MCQ & One Line)')], default='mcq', max_length=20)),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='Time limit in minutes (0 = no limit)')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Passing score percentage (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False, help_text='Randomize question order')),
                ('show_results_immediately', models.BooleanField(default=True, help_text='Show results after submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='mainApp.lecture')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, help_text='Points earned')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total possible points')),
                ('percentage_score', models.FloatField(default=0.0, help_text='Percentage score (0-100)')),
                ('is_passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt_records', to='mainApp.lectureprogress')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='mainApp.profile')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mainApp.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('quiz', 'profile', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('one_line', 'One Line Answer')], default='mcq', max_length=20)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points for correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of question in quiz')),
                ('option_a', models.CharField(blank=True, help_text='Option A', max_length=500)),
                ('option_b', models.CharField(blank=True, help_text='Option B', max_length=500)),
                ('option_c', models.CharField(blank=True, help_text='Option C', max_length=500)),
                ('option_d', models.CharField(blank=True, help_text='Option D', max_length=500)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct answer for MCQ', max_length=1)),
                ('expected_answer', models.TextField(blank=True, help_text='Expected answer for one-line question')),
                ('case_sensitive', models.BooleanField(default=False, help_text='For one-line answers: check case sensitivity')),
                ('allow_partial_match', models.BooleanField(default=True, help_text='Allow partial matching for one-line answers')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of correct answer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainApp.quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(help_text="User's submitted answer")),
                ('is_correct', models.BooleanField(default=False)),
                ('selected_option', models.CharField(blank=True, help_text='Selected option (A/B/C/D)', max_length=1)),
                ('text_answer', models.TextField(blank=True, help_text='Text answer for one-line questions')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True, help_text='Feedback on the answer')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainApp.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'ordering': ['id'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
