# Generated by Django 5.2.5 on 2026-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_quiz_quizattempt_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html_css', 'HTML/CSS'), ('sql', 'SQL')], default='python', help_text='Programming language for in-lecture code compiler', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='starter_code_template',
            field=models.TextField(blank=True, help_text='Default code shown in editor for practice exercises'),
        ),
    ]
