# Generated by Django 5.2.5 on 2026-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_course_programming_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html_css', 'HTML/CSS'), ('sql', 'SQL'), ('java', 'Java')], default='python', help_text='Programming language for in-lecture code compiler', max_length=20),
        ),
    ]
