# Generated by Django 5.2.5 on 2026-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_course_programming_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='mainApp_cou_is_acti_184ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_number'], name='mainApp_cou_course__e5b966_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['chapter', 'order'], name='mainApp_lec_chapter_eb0bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['lecture_type'], name='mainApp_lec_lecture_6e2e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['is_free_preview'], name='mainApp_lec_is_free_19f090_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseaccess',
            index=models.Index(fields=['user', 'is_active'], name='mainApp_use_user_id_51140d_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseaccess',
            index=models.Index(fields=['course', 'is_active'], name='mainApp_use_course__273872_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseaccess',
            index=models.Index(fields=['completion_percentage'], name='mainApp_use_complet_08cf48_idx'),
        ),
    ]
