# Generated by Django 5.2.5 on 2026-05-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('professional', 'Professional Blue'), ('elegant', 'Elegant Gold'), ('modern', 'Modern Gradient'), ('simple', 'Simple Classic'), ('premium', 'Premium Dark')], default='professional', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('title_text', models.CharField(default='Certificate of Completion', max_length=200)),
                ('subtitle_text', models.CharField(blank=True, default='This certificate is proudly presented to', max_length=200)),
                ('completion_text', models.CharField(default='for successfully completing the course', max_length=200)),
                ('primary_color', models.CharField(default='#1a56db', max_length=20)),
                ('secondary_color', models.CharField(default='#e5e7eb', max_length=20)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_signatures/')),
                ('seal_image', models.ImageField(blank=True, null=True, upload_to='certificate_seals/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.FloatField(default=100.0)),
                ('grade', models.CharField(blank=True, help_text='Grade achieved (e.g., A, B, C)', max_length=10)),
                ('score_percentage', models.FloatField(default=0.0, help_text='Overall course score if applicable')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/images/')),
                ('verification_url', models.URLField(blank=True, help_text='Public verification URL')),
                ('verification_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('downloaded_count', models.PositiveIntegerField(default=0)),
                ('shared_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mainApp.course')),
                ('course_access', models.OneToOneField(help_text='Link to the course access record that triggered this certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='mainApp.usercourseaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mainApp.profile')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('generated', 'Generated'), ('downloaded', 'Downloaded'), ('shared', 'Shared'), ('verified', 'Verified'), ('revoked', 'Revoked')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mainApp.certificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='mainApp_cer_certifi_265717_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='mainApp_cer_verific_956f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'course'], name='mainApp_cer_user_id_97fdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_date'], name='mainApp_cer_issued__e955f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
    ]
